version: 2.1

jobs:
  foo:
    # concurrency limit at 30
    parameters:
      size:
        type: integer
        default: 15
    parallelism: << parameters.size >>
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run:
          command: sleep 10
      - run:
          command: echo "done for Node ${CIRCLE_NODE_INDEX} / ${CIRCLE_NODE_TOTAL}"

workflows:
  main:
    jobs:
      - foo:
          size: 15
      - foo:
          size: 16
